jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout code

    - uses: actions/setup-node@v3
      name: Setup Node.js
      with:
        node-version: '18'

    - name: Install project dependencies
      run: |
        cd next-app
        npm ci

    - name: Build the Next.js application
      run: |
        cd next-app
        npm run build

    - name: Install CDK dependencies
      run: |
        cd next-app/cdk/bin
        npm install aws-cdk-lib
        npm update

    - name: CDK Deploy
      run: |
        cd next-app/cdk/bin
        npx ts-node cdk.ts
